# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_API_KEY']%>
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secret_key_base: 23639849a8064b7bc4c9bc53e37055afc8cf65cfbb4a0a511d5d18878cb79559e94bcdeb4c9a9e83875a6e13c0f70e567b007dfa53ebda8b56f314d0111b7aa8

test:
  secret_key_base: 751a5f50a7fe63088dc8c2f7b3b8d3c89e6e5ce0dc032fdb8b688c4b9db46a9e7489f9f911e1a8e75efa2cb6fb4b7ae26054a3dbea533cb0fce73469a4c03080

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
